name: Deploy Nuxt.js to VPS

jobs:
    deploy:
        name: Deploy Nuxt.js to VPS
        runs-on: ubuntu-latest

        environment: production

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22'
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SSH_HOST: ${{ secrets.SSH_HOST }}

            - name: Set up SSH
              run: |
                  # Menyiapkan konfigurasi SSH untuk akses ke VPS
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SSH_HOST: ${{ secrets.SSH_HOST }}

            - name: Deploy Application to VPS
              env:
                  SSH_HOST: ${{ secrets.SSH_HOST }}
                  SSH_USER: ${{ secrets.SSH_USER }}
                  DEPLOY_DIR: /root/www/pemira-client
              run: |
                  # Menjalankan perintah di VPS via SSH
                  echo "Deploying to VPS..."
                  ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
                    cd $DEPLOY_DIR

                    # Pull the latest changes from the main branch
                    git pull origin main

                    # Ensure NVM is loaded
                    export NVM_DIR=~/.nvm
                    source ~/.nvm/nvm.sh

                    # Install dependencies and build the application
                    npm install
                    npm run build

                    # Restart the application using pm2
                    pm2 restart 0
                  EOF
